### ISSUE TITLE
It is possible to change the title of the PhoneButtonLogin?

### ISSUE THREAD

**Issue by chiarotto** [fedepo/phoneid_iOS#2]
Hi,
I would like to replace the title of the button "Login with phone.id" with "Login" it is possible?

Thanks
Alessandro

**Comment by alyona-bachurina** [comment]
Hi, yes you can do it like this:
phoneIdButton.titleLabel.text = "Any text"

**Comment by alyona-bachurina** [comment]
Hi Alessandro.
I have updated library (version 0.1.7) and added titleText and placeholderText properties on CompactPhoneIdLoginButton - you can customize texts with them.

However there is also another more radical way of customizing any strings. 
Instead of phone.id's assets you can use your own, just need to keep same names for strings as in the phone.id. In order to do this you need:
1)  Copy content of phone.id Localizable.strings into your main bundle Localizable.strings
2)  Let phone.id know that you want to use your own NSBundle as source of strings:

```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {


        let phoneId = PhoneIdService.sharedInstance
        phoneId.componentFactory.localizationBundle = NSBundle.mainBundle()

        return true
    }
}

```

**Comment by chiarotto** [comment]
Hi thanks,

I have tried 

 [self.loginButton setTitleText:@"Phone Number"];

where 

@property (weak, nonatomic) IBOutlet CompactPhoneIdLoginButton *loginButton;

but the title doesn't change. I used storyboard as described in the guide.
I also set a breakpoint in hour code:

 public var titleText:String?{
        get{ return loginButton.titleLabel.text}
        set{ loginButton.titleLabel.text = newValue}
    }

the set is performed only once where newValue is @"Phone Number"  as expected but the title doesnt change.

**Comment by alyona-bachurina** [comment]
Hi, could you please send me your project?

**Comment by chiarotto** [comment]
It is a bit complex to send you the project. I try to use phone.id in a new empty project and to see what's happen with the title.

**Comment by chiarotto** [comment]
Hi,
now it works, the problem was that I was setting the title before this line:

[[PhoneIdService sharedInstance] logout];

thanks
